### ISSUE TITLE
Strange compile error after upgrading @keyv/redis to 2.8.1

### ISSUE THREAD

**Issue by mat813** [jaredwray/keyv#962]
**Describe the bug**
When updating @keyv/redis to 2.8.1, my code no longer compile, and I don't think the problem is in my code (as it has not changed.)

**How To Reproduce (best to provide workable code or tests!)**
The code is quite simple:

```typescript
      const keyvRedis = new KeyvRedis(redis);

      this.#keyv = new Keyv<Value>({
        store: keyvRedis,
        namespace: `${process.env.NODE_ENV ?? 'development'}:${this.cacheNamespace()}`,
      });
```

And I get this error:

```
$ tsc
node_modules/@keyv/redis/dist/index.d.ts:3:15 - error TS2305: Module '"keyv"' has no exported member 'KeyvStoreAdapter'.

3 import { type KeyvStoreAdapter, type StoredData } from 'keyv';
                ~~~~~~~~~~~~~~~~

src/class.ts:86:20 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(options?: (Options<Value> & Record<string, unknown>) | undefined): Keyv<Value, Record<string, unknown>>', gave the following error.
    Type 'KeyvRedis' is not assignable to type 'Store<string | undefined>'.
      The types returned by 'get(...)' are incompatible between these types.
        Type 'Promise<StoredData<unknown>>' is not assignable to type 'string | Promise<string | undefined> | undefined'.
          Type 'Promise<StoredData<unknown>>' is not assignable to type 'Promise<string | undefined>'.
            Type 'StoredData<unknown>' is not assignable to type 'string | undefined'.
              Type 'DeserializedData<unknown>' is not assignable to type 'string'.
  Overload 2 of 2, '(uri?: string | undefined, options?: (Options<Value> & Record<string, unknown>) | undefined): Keyv<Value, Record<string, unknown>>', gave the following error.
    Argument of type '{ store: KeyvRedis; namespace: string; }' is not assignable to parameter of type 'string'.

86       this.#keyv = new Keyv<Value>({
                      ~~~~~~~~~~~~~~~~~
87         store: keyvRedis,
   ~~~~~~~~~~~~~~~~~~~~~~~~~
88         namespace: `${process.env.NODE_ENV ?? 'development'}:${this.cacheNamespace()}`,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
89       });
   ~~~~~~~~



Found 2 errors in 2 files.

Errors  Files
     1  node_modules/@keyv/redis/dist/index.d.ts:3
     1  src/class.ts:86
```

**Comment by klippx** [comment]
Yes, this release was unexpectedly very breaking. I have exactly the same issue. 

The types export are very breaking:

`dist/index.d.ts` diff:
```diff
< declare class KeyvRedis<Value = any> extends EventEmitter {
---
> declare class KeyvRedis extends EventEmitter implements KeyvStoreAdapter {
---
<   get(key: string): GetOutput<Value>;
<   getMany(keys: string[]): GetManyOutput<Value>;
<   set(key: string, value: Value, ttl?: number): SetOutput;
<   delete(key: string): DeleteOutput;
<   deleteMany(keys: string[]): DeleteOutput;
<   clear(): ClearOutput;
<   iterator(namespace?: string): IteratorOutput;
<   has(key: string): HasOutput;
<   disconnect(): DisconnectOutput;
---
>   get<Value>(key: string): Promise<StoredData<Value> | undefined>;
>   getMany<Value>(keys: string[]): Promise<Array<StoredData<Value | undefined>>>;
>   set(key: string, value: any, ttl?: number): Promise<undefined>;
>   delete(key: string): Promise<boolean>;
>   deleteMany(keys: string[]): Promise<boolean>;
>   clear(): Promise<void>;
>   iterator(namespace?: string): AsyncGenerator<any[], void, unknown>;
>   has(key: string): Promise<boolean>;
>   disconnect(): Promise<any>;
```


You have also lost a lot of type exports in this file gone missing for some reason, which we were directly importing.

Diff `dist/types.d.ts`:
```diff
< export type IteratorOutput = AsyncGenerator<any, void, any>;
< export type GetOutput<Value> = Promise<Value | undefined>;
< export type GetManyOutput<Value> = Promise<Array<StoredData<Value | undefined>>>;
< export type SetOutput = Promise<any>;
< export type DeleteOutput = Promise<boolean>;
< export type DeleteManyOutput = Promise<boolean>;
< export type ClearOutput = Promise<void>;
< export type HasOutput = Promise<boolean>;
< export type DisconnectOutput = Promise<void>;
```

Can you please export these types in `index.d.ts` while you are at it? So we dont have to grab them from 
```ts
import type {
  ClearOutput,
  KeyvRedisOptions,
  KeyvUriOptions,
} from '@keyv/redis/dist/types.js';
```

**Comment by mlc** [comment]
I was able to work around the issue in our project by doing
```ts
import Keyv, { Store } from 'keyv';
import KeyvRedis from '@keyv/redis';

...

const redis = ....;
const keyv = new Keyv({
  store: new KeyvRedis(redis) as Store<string | undefined>,
});
```

but this feels like it should be unnecessary, and the need to do it on a patch release feels especially wrong.

**Comment by jaredwray** [comment]
@mlc, @klippx , @mat813  - thanks for finding this and we have a fix being worked on now to get this fixed. Should be out in the next few days.

**Comment by jaredwray** [comment]
@mlc @klippx and @mat813 - this is now fixed in version `2.8.2`
